import { DiscoveryNodeData, DiscoveryLinkData } from './discoveryInterfaces';

export const discoveryNodesForceDirectedData : DiscoveryNodeData[] = [
    {id: "IT", name: "IT", group: 0, nodeLabelType: "Field"},
    {id: "Application Development", name: "Application Development", group: 1, nodeLabelType: "Specialization"},
    {id: "SIT232", name: "Object-Oriented Development", group: 2, nodeLabelType: "Unit"},
    {id: "SIT305", name: "Mobile Application Development", group: 2, nodeLabelType: "Unit"},
    {id: "SIT313", name: "Full Stack Development: Secure Frontend Applications", group: 2, nodeLabelType: "Unit"},
    {id: "SIT331", name: "Full Stack Development: Secure Backend Services", group: 2, nodeLabelType: "Unit"},
    {id: "SIT323", name: "Cloud Native Application Development", group: 2, nodeLabelType: "Unit"},
    {id: "Game Development", name: "Game Development", group: 1, nodeLabelType: "Specialization"},
    {id: "SIT151", name: "Game Fundamentals", group: 2, nodeLabelType: "Unit"},
    {id: "SIT253", name: "Content Creation for Interactive Experiences", group: 2, nodeLabelType: "Unit"},
    {id: "SIT254", name: "Game Design", group: 2, nodeLabelType: "Unit"},
    {id: "SIT283", name: "Development for Virtual and Augmented Reality", group: 2, nodeLabelType: "Unit"},
    {id: "Cyber Security", name: "Cyber Security", group: 1, nodeLabelType: "Specialization"},
    {id: "SIT192", name: "Discrete Mathematics", group: 2, nodeLabelType: "Unit"},
    {id: "SIT202", name: "Computer Networks and Communication", group: 2, nodeLabelType: "Unit"},
    {id: "SIT327", name: "Network Forensics", group: 2, nodeLabelType: "Unit"},
    {id: "SIT379", name: "Ethical Hacking", group: 2, nodeLabelType: "Unit"},
    {id: "Science", name: "Science", group: 0, nodeLabelType: "Field"},
    {id: "Cell Biology and Genomics", name: "Cell Biology and Genomics", group: 1, nodeLabelType: "Specialization"},
    {id: "SLE212", name: "Biochemistry", group: 2, nodeLabelType: "Unit"},
    {id: "SLE254", name: "Genetics and Genomics", group: 2, nodeLabelType: "Unit"},
    {id: "HMM202", name: "Molecular Diagnostics", group: 2, nodeLabelType: "Unit"},
    {id: "SLE357", name: "Advanced Cell Biology", group: 2, nodeLabelType: "Unit"},
    {id: "SLE339", name: "Human Genetics and Genomics", group: 2, nodeLabelType: "Unit"},
    {id: "SLE340", name: "Genomes and Bioinformatics", group: 2, nodeLabelType: "Unit"},
    {id: "Chemistry", name: "Chemistry", group: 1, nodeLabelType: "Specialization"},
    {id: "SLE210", name: "Chemistry the Enabling Science", group: 2, nodeLabelType: "Unit"},
    {id: "SLE214", name: "Organic Chemistry", group: 2, nodeLabelType: "Unit"},
]

export const discoveryLinksForceDirectedData : DiscoveryLinkData[] = [
    {source: "IT", target: "Game Development", lineLabelType: "Field", distance: 100},
    {source: "IT", target: "Application Development", lineLabelType: "Field", distance: 100},
    {source: "IT", target: "Cyber Security", lineLabelType: "Field", distance: 100},
    {source: "SIT232", target: "Application Development", lineLabelType: "Unit", distance: 100},
    {source: "SIT305", target: "Application Development", lineLabelType: "Unit", distance: 100},
    {source: "SIT313", target: "Application Development", lineLabelType: "Unit", distance: 100},
    {source: "SIT323", target: "Application Development", lineLabelType: "Unit", distance: 100},
    {source: "SIT323", target: "SIT331", lineLabelType: "Unit", distance: 100},
    {source: "SIT151", target: "Game Development", lineLabelType: "Unit", distance: 50},
    {source: "SIT253", target: "Game Development", lineLabelType: "Unit", distance: 50},
    {source: "SIT254", target: "Game Development", lineLabelType: "Unit", distance: 50},
    {source: "SIT283", target: "Game Development", lineLabelType: "Unit", distance: 50},
    {source: "SIT192", target: "Cyber Security", lineLabelType: "Unit", distance: 50},
    {source: "SIT202", target: "Cyber Security", lineLabelType: "Unit", distance: 50},
    {source: "SIT327", target: "Cyber Security", lineLabelType: "Unit", distance: 50},
    {source: "SIT379", target: "Cyber Security", lineLabelType: "Unit", distance: 50},
    {source: "Science", target: "Cell Biology and Genomics", lineLabelType: "Field", distance: 100},
    {source: "Science", target: "Chemistry", lineLabelType: "Field", distance: 100},
    {source: "SLE212", target: "Cell Biology and Genomics", lineLabelType: "Unit", distance: 100},
    {source: "SLE254", target: "Cell Biology and Genomics", lineLabelType: "Unit", distance: 100},
    {source: "HMM202", target: "Cell Biology and Genomics", lineLabelType: "Unit", distance: 100},
    {source: "SLE357", target: "Cell Biology and Genomics", lineLabelType: "Unit", distance: 100},
    {source: "SLE339", target: "Cell Biology and Genomics", lineLabelType: "Unit", distance: 100},
    {source: "SLE340", target: "Cell Biology and Genomics", lineLabelType: "Unit", distance: 100},
    {source: "SLE210", target: "Chemistry", lineLabelType: "Unit", distance: 100},
    {source: "SLE214", target: "Chemistry", lineLabelType: "Unit", distance: 100},
  ]